AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CodeBuild-only deployer that clones a GitHub repo via Deploy Key (SSH),
  and creates a CloudFormation Change Set (no execute).
  Template name and params JSON filename are provided at build start.

Parameters:
  ProjectName:
    Type: String
    Default: cfn-changeset-deployer
    Description: CodeBuild project name.

  GithubSshRepo:
    Type: String
    Description: Git SSH URL (e.g., git@github.com:ORG/REPO.git)

  DefaultGitRef:
    Type: String
    Default: main
    Description: Default git ref (branch/tag). Can be overridden at build start.

  DeployKeySsmParamName:
    Type: String
    Default: /cfn-deployer/github/deploykey
    Description: SSM SecureString parameter name that stores the private deploy key.

  StackNamePrefix:
    Type: String
    Default: scg-point
    Description: Stack name prefix. Final stack name defaults to "<prefix>-<template>".

  TemplateRoot:
    Type: String
    Default: cfn/template/all
    Description: Root path in repo where templates exist.

  LogRetentionInDays:
    Type: Number
    Default: 30
    AllowedValues: [1,3,5,7,14,30,60,90,120,150,180,365,400,545,731,1827,3653]
    Description: CloudWatch Logs retention days.

Resources:
  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/codebuild/${ProjectName}
      RetentionInDays: !Ref LogRetentionInDays

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${ProjectName}-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # --- CloudWatch Logs ---
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*

              # --- Read deploy key from SSM SecureString ---
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${DeployKeySsmParamName}

              # SecureString decryption (if using CMK, scope this to that key ARN)
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: "*"

              # --- CloudFormation (Change Set only) ---
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:ListStacks
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: false
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
          - Name: TEMPLATE_ROOT
            Type: PLAINTEXT
            Value: !Ref TemplateRoot
          - Name: DEPLOY_KEY_SSM_PARAM
            Type: PLAINTEXT
            Value: !Ref DeployKeySsmParamName
          - Name: GIT_SSH_REPO
            Type: PLAINTEXT
            Value: !Ref GithubSshRepo
          - Name: GIT_REF
            Type: PLAINTEXT
            Value: !Ref DefaultGitRef
          - Name: STACK_NAME_PREFIX
            Type: PLAINTEXT
            Value: !Ref StackNamePrefix
          - Name: DEFAULT_GIT_REF
            Type: PLAINTEXT
            Value: !Ref DefaultGitRef

          # Intended to be overridden at build start:
          - Name: TEMPLATE
            Type: PLAINTEXT
            Value: ""
          - Name: PARAM_JSON
            Type: PLAINTEXT
            Value: ""
          # Optional override (if you want full control of stack name):
          - Name: STACK_NAME
            Type: PLAINTEXT
            Value: ""

      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref CodeBuildLogGroup
          StreamName: build-log

      Source:
        Type: NO_SOURCE
        BuildSpec: !Sub |
          version: 0.2

          phases:
            install:
              commands:
                - yum -y install jq git
                - aws --version
                - jq --version
                - git --version

            pre_build:
              commands:
                - echo "TEMPLATE=$TEMPLATE PARAM_JSON=$PARAM_JSON"
                - |
                  if [ -z "$TEMPLATE" ] || [ -z "$PARAM_JSON" ]; then
                    echo "ERROR: TEMPLATE and PARAM_JSON are required."
                    echo "  ex) TEMPLATE=alb PARAM_JSON=scg-point-product-alb.params.json"
                    exit 1
                  fi

                - GIT_REF="${GIT_REF:-$DEFAULT_GIT_REF}"
                - echo "GIT_SSH_REPO=$GIT_SSH_REPO"
                - echo "GIT_REF=$GIT_REF"

                # ---- Configure SSH deploy key ----
                - mkdir -p ~/.ssh
                - aws ssm get-parameter --name "$DEPLOY_KEY_SSM_PARAM" --with-decryption --query 'Parameter.Value' --output text > ~/.ssh/id_rsa
                - chmod 600 ~/.ssh/id_rsa
                - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
                - eval "$(ssh-agent -s)"
                - ssh-add ~/.ssh/id_rsa

                # ---- Clone repo ----
                - rm -rf repo
                - git clone --depth 1 --branch "$GIT_REF" "$GIT_SSH_REPO" repo
                - cd repo

                # ---- Locate template and params (same directory) ----
                - TEMPLATE_DIR="${TEMPLATE_ROOT}/${TEMPLATE}"
                - TEMPLATE_FILE="${TEMPLATE_DIR}/${TEMPLATE}.yaml"
                - PARAM_FILE="${TEMPLATE_DIR}/${PARAM_JSON}"

                - |
                  [ -f "$TEMPLATE_FILE" ] || (echo "ERROR: template not found: $TEMPLATE_FILE" && exit 1)
                - |
                  [ -f "$PARAM_FILE" ] || (echo "ERROR: params json not found: $PARAM_FILE" && exit 1)

                # ---- Stack and ChangeSet naming ----
                - |
                  if [ -n "$STACK_NAME" ]; then
                    FINAL_STACK_NAME="$STACK_NAME"
                  else
                    FINAL_STACK_NAME="${STACK_NAME_PREFIX}-${TEMPLATE}"
                  fi
                  echo "FINAL_STACK_NAME=$FINAL_STACK_NAME"
                - STACK_NAME="$FINAL_STACK_NAME"
                - CHANGESET_NAME="${STACK_NAME}-cs-$(date +%Y%m%d%H%M%S)"
                - echo "STACK_NAME=$STACK_NAME"
                - echo "CHANGESET_NAME=$CHANGESET_NAME"
                - echo "TEMPLATE_FILE=$TEMPLATE_FILE"
                - echo "PARAM_FILE=$PARAM_FILE"

                # ---- Convert params.json (object) to CFN parameters array ----
                - jq -c 'to_entries|map({ParameterKey:.key,ParameterValue:(.value|tostring)})' "$PARAM_FILE" > /tmp/params.cfn.json
                - cat /tmp/params.cfn.json

            build:
              commands:
                - aws cloudformation validate-template --template-body "file://$TEMPLATE_FILE"

                # Determine CREATE or UPDATE
                - |
                  if aws cloudformation describe-stacks --stack-name "$STACK_NAME" >/dev/null 2>&1; then
                    CHANGESET_TYPE="UPDATE"
                  else
                    CHANGESET_TYPE="CREATE"
                  fi
                  echo "CHANGESET_TYPE=$CHANGESET_TYPE"

                # Create Change Set (NO execute)
                - |
                  aws cloudformation create-change-set \
                    --stack-name "$STACK_NAME" \
                    --template-body "file://$TEMPLATE_FILE" \
                    --change-set-name "$CHANGESET_NAME" \
                    --change-set-type "$CHANGESET_TYPE" \
                    --parameters "file:///tmp/params.cfn.json" \
                    --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND

                - aws cloudformation describe-change-set --stack-name "$STACK_NAME" --change-set-name "$CHANGESET_NAME"

                - echo "DONE: Change Set created (not executed)."
                - echo "To execute manually (if needed):"
                - echo "aws cloudformation execute-change-set --stack-name $STACK_NAME --change-set-name $CHANGESET_NAME"

          artifacts:
            files:
              - "**/*"

Outputs:
  CodeBuildProjectName:
    Value: !Ref ProjectName
  CodeBuildRoleArn:
    Value: !GetAtt CodeBuildServiceRole.Arn
  LogGroupName:
    Value: !Ref CodeBuildLogGroup
