AWSTemplateFormatVersion: "2010-09-09"
Description: "Daily weekday 10:00 JST drift reminder (Import ConfigRuleName & SNS Topic ARN from parent stack via Export/ImportValue)"

Parameters:
  ParentStackName:
    Type: String
    Description: "Stack name of the drift detector stack (exports <StackName>-ConfigRuleName and <StackName>-SnsTopicArn)"

  ExcludeStackNames:
    Type: String
    Default: ""
    Description: "Comma-separated CloudFormation stack names to exclude from notification (e.g. stack-a,stack-b). Optional."

Resources:
  DriftReminderFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ParentStackName}-drift-reminder-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ParentStackName}-drift-reminder-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # CloudWatch Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              # Read NON_COMPLIANT resources for the rule
              - Effect: Allow
                Action:
                  - config:GetComplianceDetailsByConfigRule
                Resource: "*"

              # Publish to SNS topic from parent stack
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  Fn::ImportValue: !Sub "${ParentStackName}-SnsTopicArn"

  DriftReminderFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ParentStackName}-drift-reminder"
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt DriftReminderFunctionRole.Arn
      Timeout: 60
      Environment:
        Variables:
          CONFIG_RULE_NAME:
            Fn::ImportValue: !Sub "${ParentStackName}-ConfigRuleName"
          SNS_TOPIC_ARN:
            Fn::ImportValue: !Sub "${ParentStackName}-SnsTopicArn"
          EXCLUDE_STACK_NAMES: !Ref ExcludeStackNames
      Code:
        ZipFile: |
          import os
          import boto3
          from datetime import datetime, timezone

          config = boto3.client("config")
          sns = boto3.client("sns")

          def _fetch_non_compliant(rule_name: str):
              token = None
              results = []
              while True:
                  kwargs = {
                      "ConfigRuleName": rule_name,
                      "ComplianceTypes": ["NON_COMPLIANT"],
                      "Limit": 100,
                  }
                  if token:
                      kwargs["NextToken"] = token
                  resp = config.get_compliance_details_by_config_rule(**kwargs)

                  for ev in resp.get("EvaluationResults", []):
                      qual = ev.get("EvaluationResultIdentifier", {}).get("EvaluationResultQualifier", {})
                      rid = qual.get("ResourceId")
                      rtype = qual.get("ResourceType")
                      ts = ev.get("ResultRecordedTime")
                      results.append({
                          "resourceId": rid,
                          "resourceType": rtype,
                          "resultRecordedTime": ts.isoformat() if ts else None,
                      })

                  token = resp.get("NextToken")
                  if not token:
                      break
              return results

          def _parse_excludes(raw: str) -> set[str]:
              if not raw:
                  return set()
              items = []
              for part in raw.split(","):
                  p = part.strip()
                  if p:
                      items.append(p)
              return set(items)

          def _stack_name_from_resource_id(resource_id: str | None) -> str | None:
              """
              AWS::CloudFormation::Stack の ResourceId は通常 Stack ARN:
              arn:aws:cloudformation:<region>:<acct>:stack/<stack-name>/<id>
              から <stack-name> を抽出する
              """
              if not resource_id:
                  return None
              if ":stack/" in resource_id:
                  try:
                      # split once at ':stack/' then take first segment after it
                      after = resource_id.split(":stack/", 1)[1]
                      # after = "<stack-name>/<id>"
                      return after.split("/", 1)[0]
                  except Exception:
                      return None
              return None

          def handler(event, context):
              rule_name = os.environ["CONFIG_RULE_NAME"]
              topic_arn = os.environ["SNS_TOPIC_ARN"]
              exclude_raw = os.environ.get("EXCLUDE_STACK_NAMES", "")
              exclude_names = _parse_excludes(exclude_raw)

              non_compliant = _fetch_non_compliant(rule_name)

              if not non_compliant:
                  print(f"[OK] No NON_COMPLIANT resources for rule={rule_name}")
                  return {"status": "ok", "nonCompliantCount": 0}

              # Filter by exclude stack names
              kept = []
              excluded = []
              for item in non_compliant:
                  rid = item.get("resourceId")
                  sname = _stack_name_from_resource_id(rid)
                  if sname and sname in exclude_names:
                      excluded.append({**item, "stackName": sname})
                  else:
                      kept.append({**item, "stackName": sname})

              print(f"[INFO] total={len(non_compliant)} kept={len(kept)} excluded={len(excluded)} exclude_names={sorted(exclude_names)}")

              # If everything is excluded, do not notify
              if not kept:
                  print("[OK] All NON_COMPLIANT resources are excluded. Skipping notification.")
                  return {"status": "ok", "nonCompliantCount": len(non_compliant), "keptCount": 0, "excludedCount": len(excluded)}

              now = datetime.now(timezone.utc).isoformat()

              lines = []
              lines.append("CloudFormation Stack のドリフト（非準拠）が検出されています。")
              lines.append(f"ConfigRuleName: {rule_name}")
              lines.append(f"CheckedAt(UTC): {now}")
              if exclude_names:
                  lines.append(f"ExcludedStackNames: {', '.join(sorted(exclude_names))}")
              lines.append("")
              lines.append(f"NON_COMPLIANT resources (after exclude): {len(kept)}")
              lines.append("")

              for i, item in enumerate(kept, start=1):
                  rid = item.get("resourceId")
                  st = item.get("stackName")
                  lines.append(
                      f"{i}. {rid}  "
                      f"(stack={st}, type={item.get('resourceType')}, recorded={item.get('resultRecordedTime')})"
                  )

              message = "\n".join(lines)

              sns.publish(
                  TopicArn=topic_arn,
                  Subject=f"[Drift Reminder] NON_COMPLIANT: {len(kept)} (excluded {len(excluded)})",
                  Message=message,
              )

              return {"status": "notified", "keptCount": len(kept), "excludedCount": len(excluded)}

  DriftReminderScheduleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ParentStackName}-drift-reminder-scheduler-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ParentStackName}-drift-reminder-scheduler-invoke"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt DriftReminderFunction.Arn

  DriftReminderSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: !Sub "${ParentStackName}-drift-reminder-10am-jst"
      Description: "Weekdays 10:00 JST - check AWS Config rule and notify if NON_COMPLIANT exists"
      State: ENABLED
      ScheduleExpression: "cron(0 10 ? * MON-FRI *)"
      ScheduleExpressionTimezone: "Asia/Tokyo"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt DriftReminderFunction.Arn
        RoleArn: !GetAtt DriftReminderScheduleRole.Arn

Outputs:
  ImportedConfigRuleName:
    Description: "Imported ConfigRuleName from parent stack export"
    Value:
      Fn::ImportValue: !Sub "${ParentStackName}-ConfigRuleName"

  ImportedSnsTopicArn:
    Description: "Imported SNS Topic ARN from parent stack export"
    Value:
      Fn::ImportValue: !Sub "${ParentStackName}-SnsTopicArn"

  DriftReminderFunctionName:
    Description: "Lambda function name"
    Value: !Ref DriftReminderFunction

  DriftReminderScheduleName:
    Description: "Scheduler schedule name"
    Value: !Ref DriftReminderSchedule
