AWSTemplateFormatVersion: "2010-09-09"
Description: "Compare GitHub templates vs CloudFormation stack templates (canonical JSON) using CodeBuild only.
DeployKey is stored in SSM Parameter Store (SecureString). Pairs JSON and Python script are managed in GitHub repo. No S3/Lambda."

Parameters:
  # Git (SSH Deploy Key)
  GitRepoSshUrl:
    Type: String
    Description: "Git SSH URL (e.g., git@github.com:egstock/infra-cfn.git)"
  GitBranch:
    Type: String
    Description: "Branch name to check (free input: develop/prd/main etc.)"

  # Deploy key in SSM Parameter Store
  DeployKeySsmParamName:
    Type: String
    Default: "/cfn-diff-checker/github/deploykey"
    Description: "SSM Parameter Store name (SecureString) that stores the SSH private key (PEM)."

  # Optional: If your SecureString uses a customer-managed KMS key, specify its ARN (or leave empty)
  DeployKeyKmsKeyArn:
    Type: String
    Default: ""
    Description: "Optional. KMS Key ARN used to encrypt the SecureString in SSM. If empty, kms:Decrypt permission is not explicitly added."

  # Repo paths
  PairsJsonPath:
    Type: String
    Description: "Path in repo to pairs JSON file (e.g., config/pairs/develop.json)"
  ComparatorScriptPath:
    Type: String
    Default: "scripts/collect_and_compare_pairs.py"
    Description: "Path in repo to python comparator script (it should publish to SNS itself)"

  # Notification
  NotificationEmail:
    Type: String
    Description: "SNS email subscription target (you can add more subscribers later, including AWS Chatbot for Slack)"

  # Schedule
  ScheduleExpression:
    Type: String
    Default: "cron(0 10 ? * MON-FRI *)"
    Description: "EventBridge Scheduler cron. Default: weekdays 10:00"
  ScheduleTimezone:
    Type: String
    Default: "Asia/Tokyo"
    Description: "Timezone for scheduler (e.g., Asia/Tokyo)"

Conditions:
  HasKmsKeyArn: !Not [!Equals [!Ref DeployKeyKmsKeyArn, ""]]

Resources:
  ###################################
  # SNS
  ###################################
  DiffTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-cfn-template-diff"
      DisplayName: !Sub "CFN template diff (${AWS::StackName})"

  DiffSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref NotificationEmail
      TopicArn: !Ref DiffTopic

  ###################################
  # CodeBuild Role
  ###################################
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-codebuild-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-codebuild-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              # Read DeployKey from SSM (SecureString)
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${DeployKeySsmParamName}"

              # (Optional) KMS decrypt if SecureString is encrypted with CMK
              - !If
                - HasKmsKeyArn
                - Effect: Allow
                  Action:
                    - kms:Decrypt
                  Resource: !Ref DeployKeyKmsKeyArn
                - !Ref "AWS::NoValue"

              # CloudFormation template read
              - Effect: Allow
                Action:
                  - cloudformation:GetTemplate
                Resource: "*"

              # Publish notification
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref DiffTopic

  ###################################
  # CodeBuild Project (NO_SOURCE + SSH clone with DeployKey from SSM)
  ###################################
  TemplateCompareProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-cfn-template-compare-${GitBranch}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: GIT_REPO_SSH_URL
            Value: !Ref GitRepoSshUrl
          - Name: GIT_BRANCH
            Value: !Ref GitBranch
          - Name: PAIRS_JSON_PATH
            Value: !Ref PairsJsonPath
          - Name: COMPARATOR_SCRIPT_PATH
            Value: !Ref ComparatorScriptPath
          - Name: SNS_TOPIC_ARN
            Value: !Ref DiffTopic
          - Name: DEPLOY_KEY_SSM_PARAM
            Value: !Ref DeployKeySsmParamName
          - Name: STACK_NAME_LABEL
            Value: !Ref AWS::StackName
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - python3 --version
                - pip3 install --quiet cfn-flip
            pre_build:
              commands:
                - 'echo "Repo: ${GIT_REPO_SSH_URL}"'
                - 'echo "Branch: ${GIT_BRANCH}"'
                - 'echo "PairsJsonPath: ${PAIRS_JSON_PATH}"'
                - 'echo "ComparatorScriptPath: ${COMPARATOR_SCRIPT_PATH}"'
                - 'echo "SNS: ${SNS_TOPIC_ARN}"'
                - 'echo "DeployKeySSM: ${DEPLOY_KEY_SSM_PARAM}"'
                - mkdir -p ~/.ssh
                - aws ssm get-parameter --name "${DEPLOY_KEY_SSM_PARAM}" --with-decryption --query "Parameter.Value" --output text > ~/.ssh/id_ed25519
                - chmod 600 ~/.ssh/id_ed25519
                - ssh-keyscan github.com >> ~/.ssh/known_hosts
                - git clone --depth 1 --branch "${GIT_BRANCH}" "${GIT_REPO_SSH_URL}" repo
                - cd repo
            build:
              commands:
                - set -eu
                - python3 "${COMPARATOR_SCRIPT_PATH}"
          cache:
            paths: []

  ###################################
  # Scheduler: periodic StartBuild
  ###################################
  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-scheduler-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-scheduler-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                Resource: !GetAtt TemplateCompareProject.Arn

  DailySchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: !Sub "${AWS::StackName}-template-check-${GitBranch}"
      State: ENABLED
      ScheduleExpression: !Ref ScheduleExpression
      ScheduleExpressionTimezone: !Ref ScheduleTimezone
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: "arn:aws:scheduler:::aws-sdk:codebuild:startBuild"
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: !Sub |
          { "ProjectName": "${TemplateCompareProject}" }

Outputs:
  SnsTopicArn:
    Value: !Ref DiffTopic
    Description: "SNS Topic ARN for notifications (email/Slack(AWS Chatbot) can subscribe)"
  CodeBuildProjectName:
    Value: !Ref TemplateCompareProject
    Description: "CodeBuild project that clones repo via DeployKey (SSM) and compares GitHub templates vs CFN GetTemplate"
  ScheduleName:
    Value: !Ref DailySchedule
    Description: "Scheduler schedule name"
  DeployKeySsmParamName:
    Value: !Ref DeployKeySsmParamName
    Description: "SSM parameter name used for DeployKey"
