AWSTemplateFormatVersion: "2010-09-09"
Description: "Compare GitHub templates vs CloudFormation stack templates (canonical JSON) using CodeBuild only (DeployKey SSH clone + Git-managed pairs.json + Git-managed python script). No S3/Lambda."

Parameters:
  # Git (SSH Deploy Key)
  GitRepoSshUrl:
    Type: String
    Description: "Git SSH URL (e.g., git@github.com:egstock/infra-cfn.git)"
  GitBranch:
    Type: String
    Description: "Branch name to check (free input: develop/prd/main etc.)"

  DeployKeySecretArn:
    Type: String
    Description: "Secrets Manager ARN containing the SSH private key (SecretString is the private key PEM)."

  # Repo paths
  PairsJsonPath:
    Type: String
    Description: "Path in repo to pairs JSON file (e.g., config/pairs/develop.json)"
  ComparatorScriptPath:
    Type: String
    Default: "scripts/collect_and_compare_pairs.py"
    Description: "Path in repo to python comparator script"

  # Notification
  NotificationEmail:
    Type: String
    Description: "SNS email subscription target (you can add more subscribers later)"

  # Schedule
  ScheduleExpression:
    Type: String
    Default: "cron(0 10 ? * MON-FRI *)"
    Description: "EventBridge Scheduler cron. Default: weekdays 10:00"
  ScheduleTimezone:
    Type: String
    Default: "Asia/Tokyo"
    Description: "Timezone for scheduler (e.g., Asia/Tokyo)"

Resources:
  ###################################
  # SNS
  ###################################
  DiffTopic:
    Type: AWS::SNS::Topic
    Properties:
      # StackNameベースにして衝突を避ける
      TopicName: !Sub "${AWS::StackName}-cfn-template-diff"
      DisplayName: !Sub "CFN template diff (${AWS::StackName})"

  DiffSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref NotificationEmail
      TopicArn: !Ref DiffTopic

  ###################################
  # CodeBuild Role
  ###################################
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-codebuild-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-codebuild-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              # Read deploy key secret
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DeployKeySecretArn

              # CFN template read
              - Effect: Allow
                Action:
                  - cloudformation:GetTemplate
                Resource: "*"

              # Publish notification
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref DiffTopic

  ###################################
  # CodeBuild Project (NO_SOURCE + SSH clone)
  ###################################
  TemplateCompareProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-cfn-template-compare-${GitBranch}"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: GIT_REPO_SSH_URL
            Value: !Ref GitRepoSshUrl
          - Name: GIT_BRANCH
            Value: !Ref GitBranch
          - Name: PAIRS_JSON_PATH
            Value: !Ref PairsJsonPath
          - Name: COMPARATOR_SCRIPT_PATH
            Value: !Ref ComparatorScriptPath
          - Name: SNS_TOPIC_ARN
            Value: !Ref DiffTopic
          - Name: DEPLOY_KEY
            Type: SECRETS_MANAGER
            Value: !Ref DeployKeySecretArn
          - Name: STACK_NAME_LABEL
            Value: !Ref AWS::StackName
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - python3 --version
                - pip3 install --quiet cfn-flip
            pre_build:
              commands:
                - 'echo "Repo: ${GIT_REPO_SSH_URL}"'
                - 'echo "Branch: ${GIT_BRANCH}"'
                - 'echo "PairsJsonPath: ${PAIRS_JSON_PATH}"'
                - 'echo "ComparatorScriptPath: ${COMPARATOR_SCRIPT_PATH}"'
                - 'echo "SNS: ${SNS_TOPIC_ARN}"'
                - 'mkdir -p ~/.ssh'
                - 'echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa'
                - 'chmod 600 ~/.ssh/id_rsa'
                - 'ssh-keyscan github.com >> ~/.ssh/known_hosts'
                - 'git clone --depth 1 --branch "${GIT_BRANCH}" "${GIT_REPO_SSH_URL}" repo'
                - 'cd repo'
            build:
              commands:
                - set -eu
                # Pythonスクリプトが比較→SNS通知まで行う想定
                - python3 "${COMPARATOR_SCRIPT_PATH}"
          cache:
            paths: []

  ###################################
  # Scheduler: periodic StartBuild
  ###################################
  SchedulerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-scheduler-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-scheduler-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                Resource: !GetAtt TemplateCompareProject.Arn

  DailySchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: !Sub "${AWS::StackName}-template-check-${GitBranch}"
      State: ENABLED
      ScheduleExpression: !Ref ScheduleExpression
      ScheduleExpressionTimezone: !Ref ScheduleTimezone
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: "arn:aws:scheduler:::aws-sdk:codebuild:startBuild"
        RoleArn: !GetAtt SchedulerRole.Arn
        Input: !Sub |
          { "ProjectName": "${TemplateCompareProject}" }

Outputs:
  SnsTopicArn:
    Value: !Ref DiffTopic
    Description: "SNS Topic ARN for notifications"
  CodeBuildProjectName:
    Value: !Ref TemplateCompareProject
    Description: "CodeBuild project that clones repo via DeployKey and compares GitHub templates vs CFN GetTemplate"
  ScheduleName:
    Value: !Ref DailySchedule
    Description: "Scheduler schedule name"
